# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Siklu network device drivers.
#

#ll_temac-objs := ll_temac_main.o ll_temac_mdio.o
#obj-$(CONFIG_XILINX_LL_TEMAC) += ll_temac.o
#obj-$(CONFIG_XILINX_EMACLITE) += xilinx_emaclite.o

#xilinx_emac-objs := siklu_main.o
obj-$(CONFIG_SIKLU_EMAC) += siklu_main.o

#obj-$(CONFIG_XILINX_AXI_EMAC) += xilinx_emac.o
